// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type PageDocumentDataSlicesSlice = FaqListSlice | CtaSlice | HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Website Name field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.website_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  website_name: prismic.KeyTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Logo field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.logo
   * - **Tab**: Global Styles
   * - **Documentation**: https://prismic.io/docs/fields/image
   */;
  logo: prismic.ImageField<never>;

  /**
   * Background Color field in *Page*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: page.background_color
   * - **Tab**: Global Styles
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  background_color: prismic.ColorField;

  /**
   * Brand First Color field in *Page*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: page.brand_first_color
   * - **Tab**: Global Styles
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  brand_first_color: prismic.ColorField;

  /**
   * Brand Second Color field in *Page*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: page.brand_second_color
   * - **Tab**: Global Styles
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  brand_second_color: prismic.ColorField;

  /**
   * Title Text Color field in *Page*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title_text_color
   * - **Tab**: Global Styles
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  title_text_color: prismic.ColorField;

  /**
   * Title Text Font field in *Page*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title_text_font
   * - **Tab**: Global Styles
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  title_text_font: prismic.SelectField<
    "Inter" | "Lora" | "Poppins" | "Roboto Mono"
  >;

  /**
   * Title Text Size (px) field in *Page*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title_text_size
   * - **Tab**: Global Styles
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  title_text_size: prismic.NumberField;

  /**
   * Description Text Color field in *Page*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: page.description_text_color
   * - **Tab**: Global Styles
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  description_text_color: prismic.ColorField;

  /**
   * Description Text Font field in *Page*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: page.description_text_font
   * - **Tab**: Global Styles
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  description_text_font: prismic.SelectField<
    "Inter" | "Lora" | "Poppins" | "Roboto Mono"
  >;

  /**
   * Description Text Size (px) field in *Page*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: page.description_text_size
   * - **Tab**: Global Styles
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  description_text_size: prismic.NumberField;

  /**
   * Button Text Color field in *Page*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: page.button_text_color
   * - **Tab**: Global Styles
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  button_text_color: prismic.ColorField;

  /**
   * Button Text Font field in *Page*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: page.button_text_font
   * - **Tab**: Global Styles
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  button_text_font: prismic.SelectField<
    "Inter" | "Lora" | "Poppins" | "Roboto_Mono"
  >;

  /**
   * Button Text Size (px) field in *Page*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: page.button_text_size
   * - **Tab**: Global Styles
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  button_text_size: prismic.NumberField;

  /**
   * Button Corner Radius (px) field in *Page*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: page.button_corner_radius
   * - **Tab**: Global Styles
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  button_corner_radius: prismic.NumberField /**
   * SEO Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.seo_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  seo_title: prismic.KeyTextField;

  /**
   * SEO Description field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.seo_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  seo_description: prismic.RichTextField;

  /**
   * OG Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.og_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  og_image: prismic.ImageField<never> /**
   * Logo field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.navbar_logo
   * - **Tab**: Navbar
   * - **Documentation**: https://prismic.io/docs/fields/image
   */;
  navbar_logo: prismic.ImageField<never>;

  /**
   * Text Link field in *Page*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: page.navbar_text_link
   * - **Tab**: Navbar
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  navbar_text_link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Button Link field in *Page*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: page.navbar_button_link
   * - **Tab**: Navbar
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  navbar_button_link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * (Navbar) Logo Size (px) field in *Page*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: page.navbar_logo_size
   * - **Tab**: Navbar
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  navbar_logo_size: prismic.NumberField;

  /**
   * (Navbar) Background Color field in *Page*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: page.navbar_background_color
   * - **Tab**: Navbar
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  navbar_background_color: prismic.ColorField;

  /**
   * (Navbar) Link Text Color field in *Page*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: page.navbar_link_text_color
   * - **Tab**: Navbar
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  navbar_link_text_color: prismic.ColorField;

  /**
   * (Navbar) Link Text Font (px) field in *Page*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: page.navbar_link_text_font
   * - **Tab**: Navbar
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  navbar_link_text_font: prismic.SelectField<
    "Inter" | "Lora" | "Poppins" | "Roboto_Mono"
  >;

  /**
   * (Navbar) Link Text Size (px) field in *Page*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: page.navbar_link_text_size
   * - **Tab**: Navbar
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  navbar_link_text_size: prismic.NumberField;

  /**
   * (Navbar) Button Color field in *Page*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: page.navbar_button_color
   * - **Tab**: Navbar
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  navbar_button_color: prismic.ColorField;

  /**
   * (Navbar) Button Text Color field in *Page*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: page.navbar_button_text_color
   * - **Tab**: Navbar
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  navbar_button_text_color: prismic.ColorField;

  /**
   * (Navbar) Button Text Font field in *Page*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: page.navbar_button_text_font
   * - **Tab**: Navbar
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  navbar_button_text_font: prismic.SelectField<
    "Inter" | "Lora" | "Poppins" | "Roboto_Mono"
  >;

  /**
   * (Navbar) Button Text Size field in *Page*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: page.navbar_button_text_size
   * - **Tab**: Navbar
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  navbar_button_text_size: prismic.NumberField;

  /**
   * (Navbar) Button Corner Radius (px) field in *Page*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: page.navbar_button_corner_radius
   * - **Tab**: Navbar
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  navbar_button_corner_radius: prismic.NumberField;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = PageDocument;

/**
 * Primary content in *Cta → Default → Primary*
 */
export interface CtaSliceDefaultPrimary {
  /**
   * Title field in *Cta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.cta_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  cta_title: prismic.RichTextField;

  /**
   * Description field in *Cta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.cta_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  cta_description: prismic.RichTextField;

  /**
   * Input Placeholder field in *Cta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.cta_input_placeholder
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_input_placeholder: prismic.KeyTextField;

  /**
   * Button Link field in *Cta → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.cta_button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * (Styles) Background Color field in *Cta → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.cta_background_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  cta_background_color: prismic.ColorField;

  /**
   * (Styles) Title Text Color field in *Cta → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.cta_title_text_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  cta_title_text_color: prismic.ColorField;

  /**
   * (Styles) Title Text Font field in *Cta → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.cta_title_text_font
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  cta_title_text_font: prismic.SelectField<
    "Inter" | "Lora" | "Poppins" | "Roboto_Mono"
  >;

  /**
   * (Styles) Title Text Size (px) field in *Cta → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.cta_title_text_size
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  cta_title_text_size: prismic.NumberField;

  /**
   * (Styles) Description Text Color field in *Cta → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.cta_description_text_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  cta_description_text_color: prismic.ColorField;

  /**
   * (Styles) Description Text Font field in *Cta → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.cta_description_text_font
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  cta_description_text_font: prismic.SelectField<
    "Inter" | "Lora" | "Poppins" | "Roboto_Mono"
  >;

  /**
   * (Styles) Description Text Size (px) field in *Cta → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.cta_description_text_size
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  cta_description_text_size: prismic.NumberField;

  /**
   * (Styles) Button Color field in *Cta → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.cta_button_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  cta_button_color: prismic.ColorField;

  /**
   * (Styles) Button Text Color field in *Cta → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.cta_button_text_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  cta_button_text_color: prismic.ColorField;

  /**
   * (Styles) Button Text Font field in *Cta → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.cta_button_text_font
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  cta_button_text_font: prismic.SelectField<
    "Inter" | "Lora" | "Poppins" | "Roboto_Mono"
  >;

  /**
   * (Styles) Button Text Size (px) field in *Cta → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.cta_button_text_size
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  cta_button_text_size: prismic.NumberField;

  /**
   * (Styles) Button Corner Radius (px) field in *Cta → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.cta_button_corner_radius
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  cta_button_corner_radius: prismic.NumberField;
}

/**
 * Default variation for Cta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Cta → With Background Image → Primary*
 */
export interface CtaSliceWithBackgroundImagePrimary {
  /**
   * Title field in *Cta → With Background Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.withBackgroundImage.primary.cta_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  cta_title: prismic.RichTextField;

  /**
   * Description field in *Cta → With Background Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.withBackgroundImage.primary.cta_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  cta_description: prismic.RichTextField;

  /**
   * Input Placeholder field in *Cta → With Background Image → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.withBackgroundImage.primary.cta_input_placeholder
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_input_placeholder: prismic.KeyTextField;

  /**
   * Button Link field in *Cta → With Background Image → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.withBackgroundImage.primary.cta_button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Background Image field in *Cta → With Background Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.withBackgroundImage.primary.cta_background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cta_background_image: prismic.ImageField<never>;

  /**
   * (Styles) Background Color field in *Cta → With Background Image → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.withBackgroundImage.primary.cta_background_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  cta_background_color: prismic.ColorField;

  /**
   * (Styles) Background Image Scale (%) field in *Cta → With Background Image → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.withBackgroundImage.primary.cta_background_image_scale
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  cta_background_image_scale: prismic.NumberField;

  /**
   * (Styles) Background Img Radius (px) field in *Cta → With Background Image → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.withBackgroundImage.primary.cta_background_image_corner_radius
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  cta_background_image_corner_radius: prismic.NumberField;

  /**
   * (Styles) Title Text Color field in *Cta → With Background Image → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.withBackgroundImage.primary.cta_title_text_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  cta_title_text_color: prismic.ColorField;

  /**
   * (Styles) Title Text Font field in *Cta → With Background Image → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.withBackgroundImage.primary.cta_title_text_font
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  cta_title_text_font: prismic.SelectField<
    "Inter" | "Lora" | "Poppins" | "Roboto_Mono"
  >;

  /**
   * (Styles) Title Text Size (px) field in *Cta → With Background Image → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.withBackgroundImage.primary.cta_title_text_size
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  cta_title_text_size: prismic.NumberField;

  /**
   * (Styles) Description Text Color field in *Cta → With Background Image → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.withBackgroundImage.primary.cta_description_text_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  cta_description_text_color: prismic.ColorField;

  /**
   * (Styles) Description Text Font field in *Cta → With Background Image → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.withBackgroundImage.primary.cta_description_text_font
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  cta_description_text_font: prismic.SelectField<
    "Inter" | "Lora" | "Poppins" | "Roboto_Mono"
  >;

  /**
   * (Styles) Description Text Size (px) field in *Cta → With Background Image → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.withBackgroundImage.primary.cta_description_text_size
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  cta_description_text_size: prismic.NumberField;

  /**
   * (Styles) Button Color field in *Cta → With Background Image → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.withBackgroundImage.primary.cta_button_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  cta_button_color: prismic.ColorField;

  /**
   * (Styles) Button Text Color field in *Cta → With Background Image → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.withBackgroundImage.primary.cta_button_text_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  cta_button_text_color: prismic.ColorField;

  /**
   * (Styles) Button Text Font field in *Cta → With Background Image → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.withBackgroundImage.primary.cta_button_text_font
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  cta_button_text_font: prismic.SelectField<
    "Inter" | "Lora" | "Poppins" | "Roboto_Mono"
  >;

  /**
   * (Styles) Button Text Size (px) field in *Cta → With Background Image → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.withBackgroundImage.primary.cta_button_text_size
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  cta_button_text_size: prismic.NumberField;

  /**
   * (Styles) Button Corner Radius (px) field in *Cta → With Background Image → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.withBackgroundImage.primary.cta_button_corner_radius
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  cta_button_corner_radius: prismic.NumberField;

  /**
   * (Styles) Card Color field in *Cta → With Background Image → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.withBackgroundImage.primary.cta_card_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  cta_card_color: prismic.ColorField;

  /**
   * (Styles) Card Corner Radius (px) field in *Cta → With Background Image → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.withBackgroundImage.primary.cta_card_corner_radius
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  cta_card_corner_radius: prismic.NumberField;
}

/**
 * With Background Image variation for Cta Slice
 *
 * - **API ID**: `withBackgroundImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSliceWithBackgroundImage = prismic.SharedSliceVariation<
  "withBackgroundImage",
  Simplify<CtaSliceWithBackgroundImagePrimary>,
  never
>;

/**
 * Slice variation for *Cta*
 */
type CtaSliceVariation = CtaSliceDefault | CtaSliceWithBackgroundImage;

/**
 * Cta Shared Slice
 *
 * - **API ID**: `cta`
 * - **Description**: Cta
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSlice = prismic.SharedSlice<"cta", CtaSliceVariation>;

/**
 * Item in *Faq → Default → Primary → FAQ Items*
 */
export interface FaqListSliceDefaultPrimaryFaqItemsItem {
  /**
   * Question field in *Faq → Default → Primary → FAQ Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_list.default.primary.faq_items[].question
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  question: prismic.RichTextField;

  /**
   * Answer field in *Faq → Default → Primary → FAQ Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_list.default.primary.faq_items[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Item in *Faq → Default → Primary → Styles*
 */
export interface FaqListSliceDefaultPrimaryStylesItem {
  /**
   * Background Color field in *Faq → Default → Primary → Styles*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_list.default.primary.styles[].faq_background_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  faq_background_color: prismic.ColorField;

  /**
   * Title Text Color field in *Faq → Default → Primary → Styles*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_list.default.primary.styles[].faq_title_text_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  faq_title_text_color: prismic.ColorField;

  /**
   * Title Text Size (px) field in *Faq → Default → Primary → Styles*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_list.default.primary.styles[].faq_title_text_size
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  faq_title_text_size: prismic.NumberField;

  /**
   * Title Text Font field in *Faq → Default → Primary → Styles*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_list.default.primary.styles[].faq_title_text_font
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  faq_title_text_font: prismic.SelectField<
    "Inter" | "Lora" | "Poppins" | "Roboto_Mono"
  >;

  /**
   * Description Text Color field in *Faq → Default → Primary → Styles*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_list.default.primary.styles[].faq_description_text_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  faq_description_text_color: prismic.ColorField;

  /**
   * Description Text Font field in *Faq → Default → Primary → Styles*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_list.default.primary.styles[].faq_description_text_font
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  faq_description_text_font: prismic.SelectField<
    "Inter" | "Lora" | "Poppins" | "Roboto_Mono"
  >;

  /**
   * Description Text Size (px) field in *Faq → Default → Primary → Styles*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_list.default.primary.styles[].faq_description_text_size
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  faq_description_text_size: prismic.NumberField;

  /**
   * Question Text Color field in *Faq → Default → Primary → Styles*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_list.default.primary.styles[].faq_question_text_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  faq_question_text_color: prismic.ColorField;

  /**
   * Question Text Font field in *Faq → Default → Primary → Styles*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_list.default.primary.styles[].faq_question_text_font
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  faq_question_text_font: prismic.SelectField<
    "Inter" | "Lora" | "Poppins" | "Roboto_Mono"
  >;

  /**
   * Question Text Size (px) field in *Faq → Default → Primary → Styles*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_list.default.primary.styles[].faq_question_text_size
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  faq_question_text_size: prismic.NumberField;

  /**
   * Asnwer Text Color field in *Faq → Default → Primary → Styles*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_list.default.primary.styles[].faq_answer_text_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  faq_answer_text_color: prismic.ColorField;

  /**
   * Answer Text Font field in *Faq → Default → Primary → Styles*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_list.default.primary.styles[].faq_answer_text_font
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  faq_answer_text_font: prismic.SelectField<
    "Inter" | "Lora" | "Poppins" | "Roboto_Mono"
  >;

  /**
   * Answer Text Size (px) field in *Faq → Default → Primary → Styles*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_list.default.primary.styles[].faq_answer_text_size
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  faq_answer_text_size: prismic.NumberField;

  /**
   * Divider Color field in *Faq → Default → Primary → Styles*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_list.default.primary.styles[].faq_divider_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  faq_divider_color: prismic.ColorField;
}

/**
 * Primary content in *Faq → Default → Primary*
 */
export interface FaqListSliceDefaultPrimary {
  /**
   * Title field in *Faq → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_list.default.primary.faq_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  faq_title: prismic.RichTextField;

  /**
   * Description field in *Faq → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_list.default.primary.faq_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  faq_description: prismic.RichTextField;

  /**
   * FAQ Items field in *Faq → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_list.default.primary.faq_items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  faq_items: prismic.GroupField<
    Simplify<FaqListSliceDefaultPrimaryFaqItemsItem>
  >;

  /**
   * Styles field in *Faq → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_list.default.primary.styles[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  styles: prismic.GroupField<Simplify<FaqListSliceDefaultPrimaryStylesItem>>;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard FAQ section displaying a title, a description, and multiple collapsible Q&A pairs.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Faq*
 */
type FaqListSliceVariation = FaqListSliceDefault;

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq_list`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqListSlice = prismic.SharedSlice<
  "faq_list",
  FaqListSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_title: prismic.RichTextField;

  /**
   * Description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_description: prismic.RichTextField;

  /**
   * Button Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  hero_button_link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Image (Side) field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_side_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_side_image: prismic.ImageField<never>;

  /**
   * (Styles) Background Color field in *Hero → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_background_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  hero_background_color: prismic.ColorField;

  /**
   * (Styles) Title Text Color field in *Hero → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_title_text_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  hero_title_text_color: prismic.ColorField;

  /**
   * (Styles) Title Text Font field in *Hero → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_title_text_font
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  hero_title_text_font: prismic.SelectField<
    "Inter" | "Lora" | "Poppins" | "Roboto_Mono"
  >;

  /**
   * (Styles) Title Text Size (px) field in *Hero → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_title_text_size
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  hero_title_text_size: prismic.NumberField;

  /**
   * (Styles) Description Text Color field in *Hero → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_description_text_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  hero_description_text_color: prismic.ColorField;

  /**
   * (Styles) Description Text Font field in *Hero → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_description_text_font
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  hero_description_text_font: prismic.SelectField<
    "Inter" | "Lora" | "Poppins" | "Roboto_Mono"
  >;

  /**
   * (Styles) Description Text Size (px) field in *Hero → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_description_text_size
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  hero_description_text_size: prismic.NumberField;

  /**
   * (Styles) Button Color field in *Hero → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_button_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  hero_button_color: prismic.ColorField;

  /**
   * (Styles) Button Text Color field in *Hero → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_button_text_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  hero_button_text_color: prismic.ColorField;

  /**
   * (Styles) Button Text Font field in *Hero → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_button_text_font
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  hero_button_text_font: prismic.SelectField<
    "Inter" | "Lora" | "Poppins" | "Roboto_Mono"
  >;

  /**
   * (Styles) Button Text Size (px) field in *Hero → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_button_text_size
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  hero_button_text_size: prismic.NumberField;

  /**
   * (Styles) Button Corner Radius (px) field in *Hero → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_button_corner_radius
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  hero_button_corner_radius: prismic.NumberField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → With Background Image → Primary*
 */
export interface HeroSliceWithBackgroundImagePrimary {
  /**
   * Title field in *Hero → With Background Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withBackgroundImage.primary.hero_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_title: prismic.RichTextField;

  /**
   * Description field in *Hero → With Background Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withBackgroundImage.primary.hero_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_description: prismic.RichTextField;

  /**
   * Button Link field in *Hero → With Background Image → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withBackgroundImage.primary.hero_button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  hero_button_link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Background Image field in *Hero → With Background Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withBackgroundImage.primary.hero_background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_background_image: prismic.ImageField<never>;

  /**
   * (Styles) Background Color field in *Hero → With Background Image → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withBackgroundImage.primary.hero_background_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  hero_background_color: prismic.ColorField;

  /**
   * (Styles) Background Image Scale (%) field in *Hero → With Background Image → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withBackgroundImage.primary.hero_background_image_scale
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  hero_background_image_scale: prismic.NumberField;

  /**
   * (Styles) Background Img Radius (px) field in *Hero → With Background Image → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withBackgroundImage.primary.hero_background_image_corner_radius
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  hero_background_image_corner_radius: prismic.NumberField;

  /**
   * (Styles) Title Text Color field in *Hero → With Background Image → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withBackgroundImage.primary.hero_title_text_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  hero_title_text_color: prismic.ColorField;

  /**
   * (Styles) Title Text Font field in *Hero → With Background Image → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withBackgroundImage.primary.hero_title_text_font
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  hero_title_text_font: prismic.SelectField<
    "Inter" | "Lora" | "Poppins" | "Roboto_Mono"
  >;

  /**
   * (Styles) Title Text Size (px) field in *Hero → With Background Image → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withBackgroundImage.primary.hero_title_text_size
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  hero_title_text_size: prismic.NumberField;

  /**
   * (Styles) Description Text Color field in *Hero → With Background Image → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withBackgroundImage.primary.hero_description_text_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  hero_description_text_color: prismic.ColorField;

  /**
   * (Styles) Description Text Font field in *Hero → With Background Image → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withBackgroundImage.primary.hero_description_text_font
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  hero_description_text_font: prismic.SelectField<
    "Inter" | "Lora" | "Poppins" | "Roboto_Mono"
  >;

  /**
   * (Styles) Description Text Size (px) field in *Hero → With Background Image → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withBackgroundImage.primary.hero_description_text_size
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  hero_description_text_size: prismic.NumberField;

  /**
   * (Styles) Button Color field in *Hero → With Background Image → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withBackgroundImage.primary.hero_button_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  hero_button_color: prismic.ColorField;

  /**
   * (Styles) Button Text Color field in *Hero → With Background Image → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withBackgroundImage.primary.hero_button_text_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  hero_button_text_color: prismic.ColorField;

  /**
   * (Styles) Button Text Font field in *Hero → With Background Image → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withBackgroundImage.primary.hero_button_text_font
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  hero_button_text_font: prismic.SelectField<
    "Inter" | "Lora" | "Poppins" | "Roboto_Mono"
  >;

  /**
   * (Styles) Button Text Size (px) field in *Hero → With Background Image → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withBackgroundImage.primary.hero_button_text_size
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  hero_button_text_size: prismic.NumberField;

  /**
   * (Styles) Button Corner Radius (px) field in *Hero → With Background Image → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withBackgroundImage.primary.hero_button_corner_radius
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  hero_button_corner_radius: prismic.NumberField;

  /**
   * (Styles) Card Color field in *Hero → With Background Image → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withBackgroundImage.primary.hero_card_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  hero_card_color: prismic.ColorField;

  /**
   * (Styles) Card Corner Radius (px) field in *Hero → With Background Image → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withBackgroundImage.primary.hero_card_corner_radius
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  hero_card_corner_radius: prismic.NumberField;
}

/**
 * With Background Image variation for Hero Slice
 *
 * - **API ID**: `withBackgroundImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceWithBackgroundImage = prismic.SharedSliceVariation<
  "withBackgroundImage",
  Simplify<HeroSliceWithBackgroundImagePrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceWithBackgroundImage;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      CtaSlice,
      CtaSliceDefaultPrimary,
      CtaSliceWithBackgroundImagePrimary,
      CtaSliceVariation,
      CtaSliceDefault,
      CtaSliceWithBackgroundImage,
      FaqListSlice,
      FaqListSliceDefaultPrimaryFaqItemsItem,
      FaqListSliceDefaultPrimaryStylesItem,
      FaqListSliceDefaultPrimary,
      FaqListSliceVariation,
      FaqListSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceWithBackgroundImagePrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceWithBackgroundImage,
    };
  }
}
